import { Outfit } from "next/font/google";
import "./globals.css";
import BottomNav from "@/components/bottomNav";

const outfit = Outfit({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit",
});

export const metadata = {
  title: "MachePam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body
      className={`${outfit.className} antialiased`}
      >
        {children}
        <BottomNav />
      </body>
    </html>
  );
}
